---
- name: Install caddy (RedHat)
  block:
    - name: Add Caddy repository
      ansible.builtin.get_url:
        url: https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/repo/epel-8/group_caddy-caddy-epel-8.repo
        dest: /etc/yum.repos.d/caddy-copr.repo
        mode: '0644'

    - name: Install Caddy
      ansible.builtin.dnf:
        name: caddy
        state: present
  when: ansible_os_family == "RedHat"

- name: Install Caddy (Debian)
  block:
    - name: Add Caddy GPG key
      ansible.builtin.apt_key:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        state: present

    - name: Add Caddy repository
      ansible.builtin.apt_repository:
        repo: deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
        state: present
        filename: caddy-stable

    - name: Install Caddy
      ansible.builtin.apt:
        name: caddy
        state: present
        update_cache: yes
  when: ansible_os_family == "Debian"


- name: Ensure Caddy service is running and enabled
  ansible.builtin.systemd:
    name: caddy
    state: started
    enabled: yes

- name: Create Caddyfile for Matrix
  ansible.builtin.template:
    src: templates/Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: '0644'
  notify: Reload Caddy

